#!/bin/sh


. ./ndk-config
. ./ndk-project-config

BuildType=$1
ABI="$2"

echo ""
echo "Compiling for ABI: ${ABI}"

(${CMAKE} \
    -H"${PROJECT_ROOT}${JNI_SRC}" \
    -B"${PROJECT_ROOT}${TARGET_B_DIR}${BuildType}/${ABI}" \
    -G"Android Gradle - Ninja" \
    -DANDROID_ABI="${ABI}" \
    -DANDROID_NDK=${ANDROID_NDK_HOME} \
    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="${PROJECT_ROOT}${TARGET_LIBRARY_DIR}${ABI}" \
    -DCMAKE_BUILD_TYPE=${BuildType} \
    -DCMAKE_MAKE_PROGRAM=${NINJA} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
    -DANDROID_NATIVE_API_LEVEL=${NATIVE_API_LEVEL} \
    -DANDROID_STL="${RUNTIME}" \
    -DANDROID_TOOLCHAIN=clang) || (exit 1)
    
${CMAKE} --build "${PROJECT_ROOT}${TARGET_B_DIR}${BuildType}/${ABI}"  || (exit 1)

